### ISSUE TITLE
Is there a way to change the terms?

### ISSUE THREAD

**Issue by Spikechrisgaming** [OTBProject/OTBProject#179]
Is there a way to change the terms? As i'm not a big fan of the [[user]] term.

**Comment by Thelonedevil** [comment]
No there is no way of changing the terms. What would you prefer over "[[user]]" ?

**Comment by Spikechrisgaming** [comment]
I mostly like $user as thats what most on twitch use also.

**Comment by Thelonedevil** [comment]
Well the main reason that we went with '[[' and ']]' is that they are less likely to be part of a response. Whereas '$' at the start could be part of the response, for example: In currency. I am sure @NthPortal has other reasons for the decision as well.

**Comment by Spikechrisgaming** [comment]
I can live with [[user]] and such. It will just take me some time to get use to and stuff.

**Comment by NthPortal** [comment]
The simple answer, as @Thelonedevil said, is that there are cases where one might use a `$` in regular chat (such as if one was talking about money), but `[[` and `]]` seemed much less likely to be used.
The long answer is that the terms are a bit complicated and have a lot of options, and can't be just simply matched as "is it `[[user]]`" or "is it `[[bot]]`" for all of the terms.
Unlike other bots (for example, Nightbot only has 3 or 4 terms), we have over a dozen, and there may be a way to add custom terms in the future (it's not the highest priority, but I may implement it at some point).
Since there are many different terms, if you use either `[[` or `]]` without a valid term, the bot will stop attempting to replace terms in that message (it will "break"). `[[` and `]]` are reserved for special term use in commands, and I didn't think it would work very well to do that with `$`.
