### ISSUE TITLE
The !command list/!commands list shoulden't list every command

### ISSUE THREAD

**Issue by Spikechrisgaming** [OTBProject/OTBProject#185]
So i did the !commands list and it should only really list the "channels" commands. Not the bot type of commands...

**Comment by NthPortal** [comment]
The built-in commands (such as `!command`, `!quote`, etc.) are not substantially different from commands you add; both are stored in the same database, and both are accessed in the same way.
The only difference between them is that most of the built-in commands run scripts instead of simply sending back a response (and they have different minimum user levels for modifying certain properties of the command). Because built-in commands are treated the same as custom commands, they are also customizable (you could rename them if you really wanted to).
Once the built-in commands have been added to the database, they're not actually distinguishable from any you add, so there isn't really any way to exclude them from the command list.
(Also, since they're commands and you can run them, I'm not really sure why they shouldn't be listed.)

**Comment by Spikechrisgaming** [comment]
Well one. I only had 2 commands for testing but it was a decent wall of text. A streamer using it woulden't want to say that big wall of text and have a battle looking for there commands. Its just something that woulden't be a fun time to have to go in that wall of text to find your custom commands.

**Comment by NthPortal** [comment]
You could customize ScriptCommand.groovy and ScriptAliasMeta.groovy if you want to remove preloaded commands from the list if you want to.
